kind: pipeline
name: default

steps:
- name: build
  image: python
  commands:
  - pip install -r requirements.txt
- name: publish
  image: plugins/docker
  settings:
    username: diegokoala
    password: 
      from_secret: DockerHub
    repo: diegokoala/drone-harness-plugin
    auto_tag: true
- name: plugin test - harness pipe deploy
  image: diegokoala/drone-harness-plugin
  settings:  
    application: "Harness Demo Application"
    type: "PIPELINE"
    entityname: "CD Pipeline"
    service: "search"
    build: "v6"
    accountid:
      from_secret: harness_acctid
    apikey: 
      from_secret: harness_secret
    service_name: "order-service"
    build_number: "latest"
    artifact_source_name: "harness_todolist-sample"
    
